; PlatformIO Project Configuration
; GPIO Interrupt Rising/Falling + OLED SSD1306

[platformio]
src_dir = .

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
src_filter = +<main.cpp>
lib_deps =
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SH110X